spring.application.name=todo
spring.datasource.url=jdbc:postgresql://localhost:5432/mydb
spring.datasource.username=appu
spring.datasource.password=appu123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.ai.google.genai.api-key=AIzaSyBItYEhI2FEHUhwzLQjrJtQ1jCSpWbMIUY
spring.ai.google.genai.chat.options.model=gemini-1.5-flash